[package]
name = "ebook_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "1.2.2"
roxmltree = "0.15.0"
[dependencies.druid]
version = "0.7.0"
features = ["im", "svg", "image"]
